/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as ProviderPortalRouteImport } from './routes/provider-portal'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProvidersIdRouteImport } from './routes/providers.$id'

const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderPortalRoute = ProviderPortalRouteImport.update({
  id: '/provider-portal',
  path: '/provider-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIdRoute = ProvidersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProvidersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/cart': typeof CartRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/provider-portal': typeof ProviderPortalRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/providers/$id': typeof ProvidersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/cart': typeof CartRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/provider-portal': typeof ProviderPortalRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/providers/$id': typeof ProvidersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/cart': typeof CartRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/provider-portal': typeof ProviderPortalRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/providers/$id': typeof ProvidersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bookings'
    | '/cart'
    | '/dashboard'
    | '/insights'
    | '/provider-portal'
    | '/providers'
    | '/providers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bookings'
    | '/cart'
    | '/dashboard'
    | '/insights'
    | '/provider-portal'
    | '/providers'
    | '/providers/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bookings'
    | '/cart'
    | '/dashboard'
    | '/insights'
    | '/provider-portal'
    | '/providers'
    | '/providers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BookingsRoute: typeof BookingsRoute
  CartRoute: typeof CartRoute
  DashboardRoute: typeof DashboardRoute
  InsightsRoute: typeof InsightsRoute
  ProviderPortalRoute: typeof ProviderPortalRoute
  ProvidersRoute: typeof ProvidersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider-portal': {
      id: '/provider-portal'
      path: '/provider-portal'
      fullPath: '/provider-portal'
      preLoaderRoute: typeof ProviderPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$id': {
      id: '/providers/$id'
      path: '/$id'
      fullPath: '/providers/$id'
      preLoaderRoute: typeof ProvidersIdRouteImport
      parentRoute: typeof ProvidersRoute
    }
  }
}

interface ProvidersRouteChildren {
  ProvidersIdRoute: typeof ProvidersIdRoute
}

const ProvidersRouteChildren: ProvidersRouteChildren = {
  ProvidersIdRoute: ProvidersIdRoute,
}

const ProvidersRouteWithChildren = ProvidersRoute._addFileChildren(
  ProvidersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BookingsRoute: BookingsRoute,
  CartRoute: CartRoute,
  DashboardRoute: DashboardRoute,
  InsightsRoute: InsightsRoute,
  ProviderPortalRoute: ProviderPortalRoute,
  ProvidersRoute: ProvidersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
